# Generated by Django 5.2 on 2025-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
